# Generated by Django 5.2.7 on 2026-03-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_achievement_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='language',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
