# Generated by Django 6.0.3 on 2026-03-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_userprogress_slide_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("theory", "Теория"),
                            ("practice_drag", "Практика: порядок"),
                            ("practice_code", "Практика: код"),
                            ("quiz", "Тест"),
                        ],
                        default="theory",
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("content", models.TextField(blank=True, default="")),
                ("config", models.JSONField(blank=True, default=dict)),
                ("xp_reward", models.PositiveIntegerField(default=0)),
                ("is_required", models.BooleanField(default=True)),
                ("lesson", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="courses.lesson")),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("lesson", "order")},
            },
        ),
        migrations.CreateModel(
            name="UserStepProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("completed", models.BooleanField(default=False)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("answer_payload", models.JSONField(blank=True, default=dict)),
                ("score", models.FloatField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("step", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_progress", to="courses.lessonstep")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-completed_at", "-id"],
                "unique_together": {("user", "step")},
            },
        ),
    ]
