# Generated by Codex on 2026-03-28

import json
import re

from django.db import migrations


SUMMARY_TEXT = "Структура урока перенесена в шаги LessonStep."


def normalize_content(raw_value):
    text = str(raw_value or "")
    has_real_breaks = ("\n" in text) or ("\r" in text)
    if (not has_real_breaks) and ("\\n" in text):
        text = text.replace("\\r\\n", "\n").replace("\\n", "\n").replace("\\r", "\n")
    return text.replace("\r\n", "\n").replace("\r", "\n").strip()


def split_sections_from_text(text):
    if not text:
        return []
    normalized = re.sub(r"\s---+\s", "\n---\n", text)
    parts = [chunk.strip() for chunk in re.split(r"\n\s*---+\s*\n", normalized) if chunk.strip()]
    if parts:
        return parts

    markdown_chunks = [chunk.strip() for chunk in normalized.split("\n## ") if chunk.strip()]
    if len(markdown_chunks) > 1:
        rebuilt = []
        for idx, chunk in enumerate(markdown_chunks):
            if idx == 0 and normalized.startswith("## "):
                rebuilt.append(f"## {chunk}".strip())
            elif idx == 0:
                rebuilt.append(chunk)
            else:
                rebuilt.append(f"## {chunk}".strip())
        return rebuilt

    return [normalized]


def split_sections(raw_content):
    content = normalize_content(raw_content)
    if not content:
        return []

    try:
        parsed = json.loads(content)
        if isinstance(parsed, dict) and isinstance(parsed.get("sections"), list):
            sections = []
            for item in parsed["sections"]:
                if isinstance(item, str):
                    text = item.strip()
                elif isinstance(item, dict):
                    title = str(item.get("title") or item.get("name") or "").strip()
                    body = str(item.get("text") or item.get("content") or item.get("body") or "").strip()
                    text = f"## {title}\n{body}".strip() if title else body
                else:
                    text = ""
                if text:
                    sections.append(text)
            if sections:
                return sections
    except (TypeError, ValueError, json.JSONDecodeError):
        pass

    return split_sections_from_text(content)


def forwards(apps, schema_editor):
    Lesson = apps.get_model("courses", "Lesson")
    LessonStep = apps.get_model("courses", "LessonStep")

    lessons = Lesson.objects.filter(title__icontains="урок 1").order_by("id")
    for lesson in lessons:
        if LessonStep.objects.filter(lesson=lesson).exists():
            continue

        sections = split_sections(lesson.content)
        if not sections:
            continue

        for index, section_text in enumerate(sections, start=1):
            step_title = f"Слайд {index}"
            body_text = section_text
            first_line, _, rest = section_text.partition("\n")
            first_line = first_line.strip()
            if first_line.startswith("## "):
                parsed_title = first_line.replace("## ", "", 1).strip()
                if parsed_title:
                    step_title = parsed_title
                body_text = rest.strip()

            LessonStep.objects.create(
                lesson=lesson,
                order=index,
                step_type="theory",
                title=step_title,
                content=body_text,
                config={},
                xp_reward=0,
                is_required=True,
            )

        lesson.content = SUMMARY_TEXT
        lesson.save(update_fields=["content"])


def backwards(apps, schema_editor):
    Lesson = apps.get_model("courses", "Lesson")
    LessonStep = apps.get_model("courses", "LessonStep")

    lessons = Lesson.objects.filter(title__icontains="урок 1").order_by("id")
    for lesson in lessons:
        steps = LessonStep.objects.filter(lesson=lesson, step_type="theory").order_by("order", "id")
        if not steps.exists():
            continue

        chunks = []
        for step in steps:
            title = str(step.title or "").strip()
            content = str(step.content or "").strip()
            if title:
                chunks.append(f"## {title}\n{content}".strip())
            else:
                chunks.append(content)

        lesson.content = "\n---\n".join([chunk for chunk in chunks if chunk]).strip() or lesson.content
        lesson.save(update_fields=["content"])
        steps.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_lessonstep_userstepprogress"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
